### ISSUE TITLE
Errors in Maya 2022

### ISSUE THREAD

**Issue by JokerMartini** [JakobJK/modelChecker#11]
It throws up quite a lot of errors in Maya 2022 with just a simple test scene when using it on a few box and spheres. Are you guys still developing this tool?

**Comment by JakobJK** [comment]
Sure, can you copy/paste from the script/editor what issues you are running into? Thanks!

As in errors are you referring to the tool letting you know that the spheres and boxes generated a lot of issues? Or did the tool not run as expected? Because spheres and boxes will by default cause a lot of issues.

**Comment by JakobJK** [comment]
I'll go ahead and close this issue. Feel free to file another issue if you wanna continue the conversation.

**Comment by JokerMartini** [comment]
ill rerun the tool and test it again and report more detailed info. the tool was actually crashing repeatedly with simple a rather simple set of props used in production. Due to stability issues we ended up rolling with writing our own custom validation tool.

**Comment by JakobJK** [comment]
That's unfortunate. More information would be great.

But it sounds like you already met your needs by building your own tool. Can you share some details on your needs, and maybe some insights to your tool?
