### ISSUE TITLE
updates to the modelchecker but no PR

### ISSUE THREAD

**Issue by hannesdelbeke** [JakobJK/modelChecker#2]
this fork https://github.com/AlbertoGZ-dev/modelChecker contains nice updates
but has never been PRd in.
Then the modelChecker by Jakob was updated, and the modelChecker python file was split into separate scripts.
And so now it can't easily be merged in.
Might be worth checking it out to see if any changes could be ported across.

[Projects.zip](https://github.com/JakobJK/modelChecker/files/7921286/Projects.zip) here are the 2 modelchecker files. which can be diffed to see the new code

created a PR https://github.com/hannesdelbeke/modelChecker/pull/1 within my fork, to show the file updates. but as you can see it's a lot, and the actual functionality changes are not merged in correctly since modelChecker.py does not exist anymore.

## Updates:
- installers for every OS
- add description of every check to readme + images
- add fix functions
![image](https://user-images.githubusercontent.com/3758308/150695744-de7d45fd-a95d-42e2-961d-533f6e8076ff.png)
- add neater log, option to save log
![image](https://user-images.githubusercontent.com/3758308/150695771-48aa965d-212a-41c9-955a-295ad7fedfb2.png)
vs 
![image](https://user-images.githubusercontent.com/3758308/150695823-8724db52-9d72-45ad-a090-e9c6aef1df1f.png)

- add reset UI button
![image](https://user-images.githubusercontent.com/3758308/150695789-68af891e-808d-4b74-affc-fe4660611e0e.png)
which clears result 
![image](https://user-images.githubusercontent.com/3758308/150695798-8069705a-a2fd-4d9c-ac20-bb7321875769.png)

**Comment by JakobJK** [comment]
Hey Hannes,
I am familiar with Albertos PR, and I think he took his own great flavor on the modelChecker. He forked the repo at a time, when I intended to implement each fix function, which I have since moved away from. I'll argue why most of the changes aren't implemented in the modelChecker repo. My current philosophy towards the modelChecker is to keep minimal and as unopinionated as possible.

So for each point:
1) Installers 
In the interest of keeping things simple, I don't think installers are needed when it is simply moving a folder into an existing folder, like many other scripts for Maya.

2) Add Descriptions
I could be convinced to add this, but I do worry about imposing conventions on modelers using this by describing why you would potentially want to know about duplicated names, triangles, etc. All of these checks are not necessarily issues in every pipeline.

3) Fixer functions
I actually started wanting to implement fixer functions, but I moved away from this, in order to keep things minimal. Many of the errors have multiple ways of fixing the issues. I might change my opinion in the future, but for now, it would bloat the modelChecker into a model fixer. 

4) Add neater log & save log
Sure - we can make the log a bit neater! 
I have yet to meet anyone who actually stores and uses these logs for anything though, and I haven't found any situation where that would be useful. Logs seem to be more leaning towards a modeling publishing tool, rather than a sanity checking tool. So in the spirit of keeping the modelChecker free of unused buttons, I will not implement it. 

5) Reset button
I like this! We could do a reset UI button!

I also like how Alberto has shifted some things around in the UI! Makes a lot of sense to me.

**Comment by hannesdelbeke** [comment]
makes sense :) 
mainly made the PR since to ensure no cool bits were missed, but if you already looked at it then all is good.
my main priority is with pyblish atm, so all the GUI stuff doesn't influence me, i'm just using your commands which are amazing.
i'll close this
